MCH/MCH.Web/Models/TaskManager/TaskActionParam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MCH.Web.Models.TaskManager
{
    public class TaskActionParam
    {
        public string TaskIds { get; set; }
    }
}

MCH/MCH.Web/Models/TaskManager/TaskAlertModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MCH.Web.Models.TaskManager
{
    public class TaskAlertModel
    {
        public long TaskId { get; set; }
        public string Message { get; set; }
        public string UserName { get; set; }
        public DateTime? AlertDate { get; set; }
    }
}

MCH/MCH.Web/Models/TaskManager/TaskAssignParams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MCH.Web.Models.TaskManager
{
    public class TaskAssignParams
    {
       
        public string TaskIds { get; set; }

        public string UserIds { get; set; }
    }
}

MCH/MCH.Web/Controllers/AWBWizardController.cs
using Kendo.Mvc.UI;
using MCH.BLL.Units;
using MCH.Web.Models.AWBWizard;
using MCH.Web.Models.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Kendo.Mvc.Extensions;
using MCH.BLL.Model.Common;
using MCH.Web.Utilities;
using MCH.BLL.Model.AwbWizard;
using System.IO;
using System.Web.UI;
using MCH.BLL.Model.SpecialHandling;
using MCH.Core.Models.Common;

namespace MCH.Web.Controllers
{
    public class AWBWizardController : BaseController
    {

        #region Steps
        public PartialViewResult AWBWizardPopup(long? id, AWBWizardSteps? step)
        {
            if (step == null && id != null)
            {
                using (var unit = new AwbWizardUnit())
                {
                    step = GetAWBWizardNextStep(unit.GetAwbWizardStep(id.Value));
                }
            }
            AWBMainPopup model = new AWBMainPopup { AirwaybillId = id, Step = step.Value };
            return PartialView("AWBWizardPopup", model);
        }
        public PartialViewResult AWBStep(long? id)
        {
            using (CommonUnit unit = new CommonUnit())
            {
                ViewBag.AirCraftTypes = unit.GetAircraftTypes().Select(item => new SimpleType { Id = (int)item.Id, Name = item.Code }).ToList();
                ViewBag.AwbTypes = Enum.GetValues(typeof(AWBTypes)).Cast<AWBTypes>().Select(en => new SimpleType { Id = (int)en, Name = en.ToString() }).ToList();
            }

            AWBStep model = new AWBStep();

            using (AwbWizardUnit unit = new AwbWizardUnit())
            {
                var awb = unit.GetAwbStep(id);
                model = ConvertAWBToFrontend(awb);

            }
            return PartialView("AWBStep", model);
        }

        public ActionResult FindAWB(int accountid, string serialnumber, long originid, long destid)
        {


            using (AwbWizardUnit unit = new AwbWizardUnit())
            {
                var awb = unit.GetAwbByNumber(accountid, serialnumber, originid, destid);

                if (awb.Id > 0)
                {
                    using (CommonUnit cmunit = new CommonUnit())
                    {
                        ViewBag.AirCraftTypes = cmunit.GetAircraftTypes().Select(item => new SimpleType { Id = (int)item.Id, Name = item.Code }).ToList();
                        ViewBag.AwbTypes = Enum.GetValues(typeof(AWBTypes)).Cast<AWBTypes>().Select(en => new SimpleType { Id = (int)en, Name = en.ToString() }).ToList();
                    }

                    AWBStep model = ConvertAWBToFrontend(awb);
                    return PartialView("AWBStep", model);
                }
                else
                {
                    return Json(null);
                }

            }

        }

        private AWBStep ConvertAWBToFrontend(AwbStepModel awb)
        {
            AWBStep model = new AWBStep();

            model.AirwaybillId = awb.Id;
            model.CarrierId = awb.CarrierId;
            model.OriginId = awb.OriginId;
            model.AircraftType = awb.AircraftType;
            model.AirwaybillTypeId = awb.AwbTypeId;
            model.DestinationId = awb.DestinationId;

            model.AccountInformationText = awb.AccountInformationText;

            //    model.GoodsDescription = awb.GoodsDescription;
            model.AirwaybillSerialNumber = awb.AwbSerialNumber;
            //    model.OtherServiceRequests = awb.OtherServiceRequests;
            //    model.SpecialServiceRequests = awb.SpecialServiceRequests;
            //model.AccountInformation = awb.AccountInformation.Select(a => new Code
            //{
            //    Id = a.Id,
            //    CodeId = a.CodeId,
            //    CodeNote = a.CodeNote
            //}).ToList();
            model.IssuingCarriersAgent = new Agent
            {
                Id = awb.IssuingCarriersAgent.Id,
                City = awb.IssuingCarriersAgent.City,
                Name = awb.IssuingCarriersAgent.Name,
                IATACode = awb.IssuingCarriersAgent.IataCode,
                CASSAddress = awb.IssuingCarriersAgent.CassAddress,
                AccountNumber = awb.IssuingCarriersAgent.AccountNumber,
                ParticipantIdentfierId = awb.IssuingCarriersAgent.ParticipantIdentfierId
            };
            model.Shipper = new Partner
            {
                Id = awb.Shipper.Id,
                Fax = awb.Shipper.Fax,
                Name = awb.Shipper.Name,
                City = awb.Shipper.City,
                Type = PartnerType.Shipper,
                Phone = awb.Shipper.Phone,
                Postal = awb.Shipper.Postal,
                StateId = awb.Shipper.StateId,
                Address1 = awb.Shipper.Address1,
                CountryId = awb.Shipper.CountryId,
                AccountNumber = awb.Shipper.AccountNumber
            };
            model.Consignee = new Partner
            {
                Id = awb.Consignee.Id,
                Fax = awb.Consignee.Fax,
                Name = awb.Consignee.Name,
                City = awb.Consignee.City,
                Type = PartnerType.Consignee,
                Phone = awb.Consignee.Phone,
                Postal = awb.Consignee.Postal,
                StateId = awb.Consignee.StateId,
                Address1 = awb.Consignee.Address1,
                CountryId = awb.Consignee.CountryId,
                AccountNumber = awb.Consignee.AccountNumber,
            };
            model.Flights = awb.Flights.Select(f => new Flight
            {
                Id = f.Id,
                FlightNo = f.FlightNo,
                FlightDate = f.FlightDate,
                FlightToId = f.FlightToId.ToString(),
                FlightFromId = f.FlightFromId.ToString(),
                FlightCarrierId = f.CarrierId.ToString()
            }).ToList();

            if (awb.SenderReferences.FirstOrDefault() != null)
            {
                model.AirportId = awb.SenderReferences.First().AirportId;
                model.ParticipantCode = awb.SenderReferences.First().ParticipantCode;
                model.ParticipantIdentfierId = awb.SenderReferences.First().ParticipantIdentifierId;
                model.FileReference = awb.SenderReferences.First().FileReference;
            }

            // Do not remove this ever
            //var acInfCount = 6 - model.AccountInformation.Count();
            //for (int i = 0; i < acInfCount; i++)
            //{
            //    Code code = new Code();
            //    model.AccountInformation.Add(code);
            //}

            var flCount = 3 - model.Flights.Count();
            for (int i = 0; i < flCount; i++)
            {
                Flight code = new Flight();
                model.Flights.Add(code);
            }
            //

            return model;
        }
        public PartialViewResult SaveAWBStep(AWBStep step)
        {
            //step.Flights = step.Flights.Where(fl => fl.FlightFromId != null).ToList();
            //   step.AccountInformation = step.AccountInformation.Where(ac => ac.CodeId != null || !String.IsNullOrWhiteSpace(ac.CodeNote)).ToList();

            //var flights = ConvertToXml<Flight>(step.Flights);
            //  var accountInfo = ConvertToXml<Code>(step.AccountInformation);

            var datamodel = ConvertAWBToBackend(step);

            using (AwbWizardUnit unit = new AwbWizardUnit())
            {
                step.AirwaybillId = unit.SaveAwbStep(datamodel, SessionManager.UserInfo.UserLocalId, SessionManager.UserInfo.DefaultWarehouseId.Value);
            }

            return ChargesStep(step.AirwaybillId);
        }

        private AwbStepModel ConvertAWBToBackend(AWBStep step)
        {

            AwbStepModel datamodel = new AwbStepModel();

            datamodel.Id = step.AirwaybillId;
            datamodel.CarrierId = (int)step.CarrierId;
            datamodel.OriginId = step.OriginId;
            datamodel.AircraftType = step.AircraftType.Value;
            datamodel.AwbTypeId = step.AirwaybillTypeId;
            datamodel.DestinationId = step.DestinationId;

            datamodel.AccountInformationText = step.AccountInformationText;
            datamodel.AwbSerialNumber = step.AirwaybillSerialNumber;

            datamodel.IssuingCarriersAgent = new AgentModel
            {
                Id = step.IssuingCarriersAgent.Id,
                City = step.IssuingCarriersAgent.City,
                Name = step.IssuingCarriersAgent.Name,
                IataCode = step.IssuingCarriersAgent.IATACode,
                CassAddress = step.IssuingCarriersAgent.CASSAddress,
                AccountNumber = step.IssuingCarriersAgent.AccountNumber,
                ParticipantIdentfierId = step.IssuingCarriersAgent.ParticipantIdentfierId
            };
            datamodel.Shipper = new CustomerModel
            {
                Id = step.Shipper.Id
            };
            datamodel.Consignee = new CustomerModel
            {
                Id = step.Consignee.Id
            };
            datamodel.Flights = step.Flights.Where(f=>f.FlightFromId!=null).Select(f => new FlightModel
            {
                Id = f.Id,
                FlightNo = f.FlightNo,
                FlightDate = f.FlightDate,
                FlightToId = long.Parse(f.FlightToId),
                FlightFromId = long.Parse(f.FlightFromId),
                CarrierId = long.Parse(f.FlightCarrierId)
            }).ToList();

            var sd = new List<SenderReferenceModel>();
           
           sd.Add( new SenderReferenceModel {

             AirportId = step.AirportId,
                ParticipantCode = step.ParticipantCode,

MCH/MCH.Web/Controllers/TaskManagerController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using MCH.Web.Models;
using MCH.BLL.Units;
using System.Collections;
using MCH.Web.Models.TaskManager;
using MCH.Web.Utilities;
using MCH.BLL.Model.Enum;

namespace MCH.Web.Controllers
{
    public class TaskManagerController : Controller
    {
        public PartialViewResult TaskList() 
        {
            return PartialView("TaskList");
        }


        public JsonResult TaskListDatasource([DataSourceRequest] DataSourceRequest request)
        {
            IEnumerable<TasksGridRow> tmpList = null;
            DataSourceResult tmpResult = null;
            using (TasksUnitOfWork taskUnit = new TasksUnitOfWork())
            {
                tmpList = taskUnit.Context.MCHTaskManagerViews.Select(t => new TasksGridRow
                 {
                     AirlineCode = t.Airline,
                     Alerts = t.AlertCount,
                     AssignedTo = t.TaskAssignees,
                     Department = t.Department,
                     DepartmentId = t.DepartmentId,
                     DueOn = t.DueOn,
                     Ended = t.EndDate,
                     EntityId = t.EntityId,
                     EntityTypeId = t.EntityTypeId,
                     Indicators = t.Indicators,
                     Pieces = t.Pieces,
                     Priority = t.TaskPriority,
                     Progress = t.TaskProgress,
                     Reference = t.Reference,
                     Reopened = t.IsReopened,
                     Started = t.StartDate,
                     Status = t.TaskStatus,
                     TaskDate = t.TaskDate,
                     TaskId = t.TaskId,
                     TaskLocation = t.WarehouseLocation,
                     TaskType = t.TaskType,
                     TaskTypeId = t.TaskTypeId,
                     ULDs = t.Ulds,
                     Weight = t.Weight,
                     WeightUOM = t.WeightUOM,
                     WarehouseId = t.WarehouseId
                 });
               

                tmpResult = tmpList.ToDataSourceResult(request);
            }


            return Json(tmpResult, JsonRequestBehavior.AllowGet);
        }


        public PartialViewResult GetTaskAlertsView(long taskId)
        {
            return PartialView("_wndTaskAlerts", taskId);
        }

        public JsonResult TaskAlertsDS([DataSourceRequest] DataSourceRequest request, long taskId)
        {
            List<TaskAlertModel> tmpAlerts = null;
            using (TasksUnitOfWork tasksUnit = new TasksUnitOfWork())
            {
                var tmpTaskAlerts = tasksUnit.GetTaskAlerts(taskId);

                tmpAlerts = tmpTaskAlerts.Select(a => new TaskAlertModel { 
                    TaskId = taskId,
                    AlertDate = a.Date,
                    Message = a.AlertMessage,
                    UserName = a.UserName
                }).ToList();
            }

            return Json(tmpAlerts.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetTaskUserAssignView(long[] taskIds)
        {
            return PartialView("_wndTaskUserAssign", taskIds);
        }

        public PartialViewResult GetTaskInstrAssignView(long[] taskIds)
        {
            return PartialView("_wndTaskInstrAssign", taskIds);
        }

        [HttpPost]
        public JsonResult AssignTasksToUser(TaskAssignParams model)
        {
            using (TasksUnitOfWork tasksUnit = new TasksUnitOfWork())
            {
                try
                {
                    var tmpUserIds = model.UserIds.Split().Select(t => Int64.Parse(t)).ToArray();
                    var tmpTaskIds = model.TaskIds.Split().Select(t=> Int64.Parse(t)).ToArray();
                    tasksUnit.AssignTasksToUsers(tmpTaskIds, tmpUserIds, SessionManager.UserInfo.UserLocalId);

                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { ErrorMessage = "Internal Error during reopening the task." }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult AssignTasksInstr(TaskInstrParms model)
        {
            using (TasksUnitOfWork tasksUnit = new TasksUnitOfWork())
            {
                try
                {
                    var tmpTaskIds = model.TaskIds.Split(',').Select(t => Int64.Parse(t)).ToArray();
                    tasksUnit.AddInstructions(tmpTaskIds,  SessionManager.UserInfo.UserLocalId ,model.Instructions);

                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { ErrorMessage = "Internal Error during reopening the task." }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult ReopenTasks(TaskActionParam model)
        {
            using (TasksUnitOfWork tasksUnit = new TasksUnitOfWork())
            {
                try
                {
                    var tmpTaskIds = model.TaskIds.Split(',').Select(e => Int64.Parse(e)).ToArray();
                    var actionResult = tasksUnit.ReopenTasks(tmpTaskIds, SessionManager.UserInfo.UserLocalId);

                    return Json(new { ActionResults = actionResult}, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { ErrorMessage = "Internal Error during reopening the task." }, JsonRequestBehavior.AllowGet);
                }
            }
        }


        [HttpPost]
        public JsonResult CancelTasks(TaskActionParam model)
        {
            using (TasksUnitOfWork tasksUnit = new TasksUnitOfWork())
            {
                try
                {
                    var tmpTaskIds = model.TaskIds.Split(',').Select(e => Int64.Parse(e)).ToArray();
                    var actionResult = tasksUnit.CancelTasks(tmpTaskIds, SessionManager.UserInfo.UserLocalId);

                    return Json(new { ActionResults = actionResult }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { ErrorMessage = "Internal Error during canceling the task." }, JsonRequestBehavior.AllowGet);
                }
            }
        }

    }
}

MCH/MCH.Web/Views/TaskManager/TaskList.cshtml

<script type="text/javascript" src="@Url.Content("~/Scripts/task-management/task-manager-grid.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.maskedinput.min.js")"></script>

<script>
    window.TaskManager = new TaskManagerGrid("tableTaskManagerList",
        {
            GetTaskAlerts: '@Url.Action("GetTaskAlertsView", "TaskManager")',
            GetEntityViewerByType: '@Url.Action("GetEntityViewerByType", "EntityViewers")',
            GetTaskUserAssignView: '@Url.Action("GetTaskUserAssignView", "TaskManager")',
            GetTaskInstrAssignView: '@Url.Action("GetTaskInstrAssignView", "TaskManager")',
            GetCargoAcceptanceView: '@Url.Action("GetCargoAcceptanceView", "CargoAcceptance")',
            GetCargoDischargeView: '@Url.Action("GetCargoDischargeView", "CargoDischarge")',
            ReopenTasks: '@Url.Action("ReopenTasks", "TaskManager")',
            CancelTasks: '@Url.Action("CancelTasks", "TaskManager")',

            GetAWBWizarView: '@Url.Action("AWBWizardPopup", "AWBWizard")',
            GetHWBWizarView: '@Url.Action("HWBAddEdit", "AWBWizard")',
            CancelAwbWizard: '@Url.Action("CancelWizard", "CargoAcceptance")',
            CancelDisWizard: '@Url.Action("CancelWizard", "CargoDischarge")',
            GetHWBExtraPopupView: '@Url.Action("HWBExtraPopup", "AWBWizard")',
        });

    $("#TaskManagerEvents").on("tm-event:assignUser", function (event, args) {
        window.TaskManager.onUserAssigned();
    });

    $("#TaskManagerEvents").on("tm-event:assignInstr", function (event, args) {
        window.TaskManager.onInstrAssigned();
    });

    function selectGridRow(grid, rowIndex) {

        if (!grid || !grid.tbody) return false;
        row = grid.tbody.find(">tr:not(.k-grouping-row)").eq(rowIndex);
        grid.select(row);
    }

    function taskManagerGridReady(e) {
        var tmpGrid = $("#tableTaskManagerList").data("kendoGrid");
        selectGridRow(tmpGrid, 0);
    }

    function GetIndicatorIcons(commaSeparated) {
        var iconsText = "";
        if (commaSeparated && commaSeparated != null) {
            var tmpIconName = commaSeparated.split(',');

            for (var i = 0; i < tmpIconName.length; i++) {
                if (tmpIconName[i] != " ") {
                    var tmpIconsHtml = "<img style='width:20px' src=@Url.Content("~/Content/assets/images/indicators/")" + tmpIconName[i].trim() + ".png  title='" + tmpIconName[i] + "' />";
                    iconsText = iconsText + " " + tmpIconsHtml;
                }
            }
        }
        return iconsText;
    }

</script>


<div class="innerAll spacing-x1 cm-right-content">
    <div class="box-generic cm-white-content" id="tbTaskManagement">
        @(Html.Kendo().Grid<MCH.Web.Models.TasksGridRow>().Name("tableTaskManagerList")
                .Columns(c =>
                {
                    c.Bound(o => o.WarehouseId).Hidden(true);
                    c.Bound(o => o.TaskId).Visible(false);
                    c.Bound(o => o.TaskTypeId).Hidden(true);
                    c.Bound(o => o.TaskType).Width(120);
                    c.Bound(o => o.Alerts)
                        .ClientTemplate(@"<button type='button' class='k-button-tmpl' onclick='window.TaskManager.showTaskAlerts(#=TaskId#)'>#=Alerts#</button>")
                        .Width(80);
                    c.Bound(o => o.Indicators).ClientTemplate("#= GetIndicatorIcons(Indicators) #").Width(150);
                    c.Bound(o => o.Priority)
                        .ClientTemplate("#= Priority ? '<img style=width:20px src=" + Url.Content("~/Content/images/priority.png") + " title=Priority /> ' : '' #")
                        .HeaderTemplate("<img style=width:20px src=" + Url.Content("~/Content/images/priority.png") + " title=Priority />")
                        .Filterable(false).Width(40);
                    c.Bound(o => o.AirlineCode).Title("Airline").Width(100);
                    c.Bound(o => o.Reference).Width(200);
                    c.Bound(o => o.TaskDate).Format("{0:MM/dd/yyyy}").Width(100);
                    c.Bound(o => o.DueOn).Format("{0:MM/dd/yyyy HH:mm}").Width(100);
                    c.Bound(o => o.Status).Width(80);
                    c.Bound(o => o.Progress).ClientTemplate("#=Progress# %").Width(100);
                    c.Bound(o => o.Reopened).ClientTemplate("#= Reopened ? '<img src=" + Url.Content("~/Content/images/reopen.png") + " title=Reopened />' : ''#").HeaderTemplate("<img src=" + Url.Content("~/Content/images/reopen.png") + " title=Reopened />").Width(35).Filterable(false);
                    c.Bound(o => o.AssignedTo).Width(100);
                    c.Bound(o => o.Started).Format("{0:MM/dd/yyyy HH:mm}").Width(100);
                    c.Bound(o => o.Ended).Format("{0:MM/dd/yyyy HH:mm}").Width(100);
                    c.Bound(o => o.ULDs).Title("ULDs").Width(80);
                    c.Bound(o => o.Pieces).Width(100);
                    c.Bound(o => o.Weight).ClientTemplate("#=Weight != null ? Weight:''# #=WeightUOM != null ? WeightUOM : ''#").Width(90);
                    c.Bound(o => o.TaskLocation).Title("Location").Width(100);
                    c.Bound(o => o.Department).Width(110);
                    c.Bound(o => o.DepartmentId).Hidden(true);
                }
        )
                .Events(e => e.DataBound("taskManagerGridReady"))
        .DataSource(e => e.Ajax()
                    .Read(r =>
                        r.Action("TaskListDatasource", "TaskManager"))
                        .PageSize(20)
                    )
                    .Filterable()
                    .Sortable()
                    .Selectable(s => s.Mode(GridSelectionMode.Multiple))
                    .Scrollable()
                    .Pageable()
                    .Resizable(r => r.Columns(true))
                            .ToolBar(t =>
                            {
                                t.Template(
                                    @<text>
                                        @Html.Partial("_TaskListToolbar")
                                    </text>);
                            }).HtmlAttributes(new { style = "height:100%; min-height:1000px;" })

        )

    </div>
</div>
<div class="cm-window-wrapper" id="TaskManagerEvents">

    @(Html.Kendo().Window().Name("wndTMAlert").Draggable(true).Visible(false).Modal(true))

    @(Html.Kendo().Window().Name("wndTMActionConfirm").Draggable(true).Visible(false).Modal(true))

    @(Html.Kendo().Window().Name("wndTMActionPerform").Draggable(true).Visible(false).Modal(true))

    @(Html.Kendo().Window().Name("wndTMShowTaskDetails").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndTMAddTaskView")
    .Actions(a => a.Minimize().Maximize().Close())
    .Draggable(true).Visible(false)
            //.Events(e=>e.Open("resizeKendoWindow"))
    .Resizable()
    .Modal(true))

    @(Html.Kendo().Window().Name("wndTMAddTaskPopupWizard").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndTMAddHWBPopup").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndTMTaskViewer").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndAddressBook").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndAddEditPartner").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

    @(Html.Kendo().Window().Name("wndAddEditRate").Actions(a => a.Minimize().Maximize().Close()).Draggable(true).Visible(false).Resizable().Modal(true))

</div>

<script type="text/javascript">
    $(document).ready(function () {
        window.TaskManager.init();
        window.TaskManager.filterTaskManagerGrid();
    })
</script>

MCH/MCH.Web/Views/TaskManager/_wndTaskAlerts.cshtml
@model long
@(Html.Kendo().Grid<MCH.Web.Models.TaskManager.TaskAlertModel>()
.Name("gridTaskAlerts")
.Columns(c=> {
    c.Bound(o=> o.TaskId).Hidden(true);
    c.Bound(o=> o.Message);
    c.Bound(o => o.UserName);
    c.Bound(o => o.AlertDate).Format("{0:MM/dd/yyyy HH:mm}");
})
.DataSource(d => d.Ajax().Read(r => r.Action("TaskAlertsDS", "TaskManager", new { taskId = Model })))
)

MCH/MCH.Web/Views/TaskManager/_wndTaskInstrAssign.cshtml
@model long[]

<script>
    function assignTaskInstruction() {
        tmpValidator = $("#frmAddTaskInstructions").kendoValidator().data("kendoValidator");

        var validationResult = tmpValidator.validate();
        if (validationResult) {
            $.ajax({
                url: '@Url.Action("AssignTasksInstr", "TaskManager")',
                type: "POST",
                data: { taskIds: $("#hdnTaskList").val(), Instructions: $("#taskInstructions").val() },
                dataType: "json",
                traditional: true,
                success: function (result) {
                    $("#taskInstructions").val('');
                    $("#TaskManagerEvents").trigger("tm-event:assignInstr");
                }
            }).fail(function () {
                me.common.popup("Error", "Something went wrong, please try again later.");
            });
        }
    }
</script>

<div class="row">
    <form id="frmAddTaskInstructions" class="form-horizontal form-widgets col-md-12">
        @Html.Hidden("hdnTaskList", String.Join(",", Model))
        <div class="form-group">
            <label for="Instructions" class="col-lg-3 control-label">Instructions : </label>
            <div class="col-lg-9">
                @Html.TextArea("taskInstructions", new { rows = "4", required = "required", name = "Instrutions", style = "width:100%" })
                @Html.ValidationMessage("taskInstructions", new { @class = "k-invalid-msg" })
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-md-12 pull-right">
        <div class="btn-group-sm pull-right">
            <input type="button" class="k-button op-window-close" value="Cancel" />
            <input type="button" class="k-button k-primary" value="Assign" onclick="assignTaskInstruction()" />
        </div>
    </div>
</div>




MCH/MCH.Web/Views/TaskManager/_wndTaskUserAssign.cshtml
@model long[]

<script>
    function assignTaskUsers() {

        var tmpData = { taskIds: $("#hdnTaskList").val(), userIds: $("#ddlUsersForTaskAssign").data("kendoMultiSelect").value().join() };

        $.ajax({
            url: '@Url.Action("AssignTasksToUser", "TaskManager")',
            type: "POST",
            data: tmpData,
            dataType: "json",
            traditional: true,
            success: function (result) {
                $("#TaskManagerEvents").trigger("tm-event:assignUser");
            }
        }).fail(function () {
            me.common.popup("Error", "Something went wrong, please try again later.");
        });
    }
</script>

<div class="row">
    <form class="form-horizontal form-widgets col-md-12">
        @Html.Hidden("hdnTaskList", String.Join(",", Model))
        <div class="form-group">
            <label for="Users" class="col-lg-4 control-label">Select Users : </label>
            <div class="col-lg-8">
                @(
 Html.Kendo().MultiSelect().Name("ddlUsersForTaskAssign")
    .DataSource(d => d.Read(r => r.Action("GetUsers", "Common"))).DataTextField("name").DataValueField("id")
                )
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-md-12 pull-right">
        <div class="btn-group-sm pull-right">
            <input type="button" class="k-button op-window-close" value="Cancel" />
            <input type="button" class="k-button k-primary" value="Assign" onclick="assignTaskUsers()" />
        </div>
    </div>
</div>
