MCH/MCH.Web/Models/WarehouseManagement/WarehouseManagement.cs
using MCH.BLL.DAL;
using MCH.BLL.Model.AwbWizard;
using MCH.BLL.Model.Customs;
using MCH.BLL.Model.SpecialHandling;
using MCH.BLL.Model.Warehouse;
using MCH.Web.Models.Common;
using MCH.Web.Models.Shared;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCH.Web.Models.WarehouseManagement
{

    public class WarehouseManagement
    {
        public long? StationId { get; set; }

        public long? WarehouseId { get; set; }

        public long? RegionId { get; set; }

        public long? LocationId { get; set; }
    }


    public class ShipmentTab
    {
        public long StationId { get; set; }

        public long? WareHouseId { get; set; }
    }
    public class WarehouseShipmentInventory
    {

        public long ? ShipmentId { get; set; }

        public bool ? IsOSD { get; set; }

        public string SpecialHandlingsIndicators { get; set; }

        public  SpecialHandlingIndicator SpecialHandlingsSource { get; set; }

        public string ShipmentReference { get; set; }
        public string Warehouse { get; set; }

        public string Origin { get; set; }

        public string Destination { get; set; }

        public string Location { get; set; }

        public int? Pieces { get; set; }

        public int? TotalPieces { get; set; }


        public DateTime? FirstScan { get; set; }
        public DateTime? LastScan { get; set; }

        public string User { get; set; }
        public double? Duration
        {
            get
            {
                double? tmpHoures = null;
                if (this.LastScan.HasValue && this.FirstScan.HasValue)
                {
                    tmpHoures = (this.LastScan.Value - this.FirstScan.Value).TotalHours;
                }
                return tmpHoures;
            }
        }
        public string Shipper { get; set; }
        public string Consignee { get; set; }

        private double? totalWeight;
        public double? TotalWeight { get { return this.totalWeight; } set { this.totalWeight = value; } }

        public string WeightUOM { get; set; }
    }

    public class WarehouseLocationInventory
    {
        public long WarehouseLocationId { get; set; }
        public string Warehouse { get; set; }
        public string Location { get; set; }
        public int? Pieces { get; set; }
        public int? TotalPieces { get; set; }
        public DateTime? LastScan { get; set; }
        public string User { get; set; }
        public double? TotalWeight { get; set; }
        public string WeightUOM { get; set; }

    }


    public class LocationAddEdit
    {
        public long? LocationId { get; set; }

        public long? StationId { get; set; }

        public long? WarehouseId { get; set; }

        public int? RegionId { get; set; }

        public long? LocationTypeId { get; set; }

        public string LocationName { get; set; }

        public string BarCode { get; set; }

        public WarehouseLocationBo ToBusinessModel()
        {

            return new WarehouseLocationBo
                {
                    Barcode = this.BarCode,
                    LocationId = this.LocationId,
                    LocationName = this.LocationName,
                    LocationTypeId = this.LocationTypeId,
                    ZoneId = this.RegionId,
                    PortId = this.StationId,
                    WarehouseId = this.WarehouseId
                };
        }
    }

    public class WarehouseAddEdit
    {
        public long? WarehouseId { get; set; }

        public long? StationId { get; set; }

        public int? ShellWarehouseId { get; set; }
        public string WarehouseName { get; set; }

        public string AliasName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public int? StateId { get; set; }
        public int? CountryId { get; set; }

        public string Postal { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ManagerName { get; set; }
        public string GeoLocation { get; set; }

        public double ? Latitude { get; set; }
        public double ? Longitude { get; set; }

        public WarehouseBo ToBusinesModel() 
        {
            return new WarehouseBo
            {
                Address1 = this.Address1,
                Address2 = this.Address2,
                City = this.City,
                Code = this.AliasName,
                CountryId = this.CountryId,
                FirmCode = string.Empty,
                Id = this.WarehouseId,
                Name = this.WarehouseName,
                Phone = this.Phone,
                PortId = this.StationId,
                PostalCode = this.Postal,
                SateId = this.StateId,
                ShellWarehouseId = this.ShellWarehouseId,
                Supervisor = this.ManagerName,
                GeoLocation = this.GeoLocation,
                ContactEmail = this.Email,
            };
        }

    }

    public class RegionAddEdit
    {
        public long? RegionId { get; set; }
        public long? StationId { get; set; }
        public long? WarehouseId { get; set; }

        public string RegionName { get; set; }


        public WarehouseZoneBo ToBusinessModel()
        {
            return new WarehouseZoneBo
                {
                    ZoneId = this.RegionId,
                    PortId = this.StationId,
                    Name = this.RegionName,
                    WarehouseId = this.WarehouseId
                };
        }
    }


}

MCH/MCH.Web/Controllers/WarehouseManagementController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using MCH.BLL.Units;
using MCH.Web.Models.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MCH.Web.Utilities;
using MCH.Web.Models.WarehouseManagement;
using System.Web.Security.AntiXss;
using System.Web.Util;
using MCH.Web.Filters;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using MCH.BLL.Model.Enum;
using MCH.Web.Models.Common;
using MCH.BLL.Model.Warehouse;
using MCH.BLL.DAL.Data;

namespace MCH.Web.Controllers
{

    public class WarehouseManagementController : Controller
    {
        private MCHDBEntities Context = null;

        public WarehouseManagementController()
        {
            this.Context = new MCHDBEntities();
        }

        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            base.OnActionExecuted(filterContext);
        }

        protected override void OnResultExecuted(ResultExecutedContext filterContext)
        {
            base.OnResultExecuted(filterContext);
            this.Context.Dispose();
            this.Context = null;
        }

        // GET: WarehouseManagement
        public PartialViewResult WarehouseManagementTabstrip()
        {
            ViewBag.ManageTypes = new List<SimpleType>
            {
                    new SimpleType { Id = 1, Name = "Manage Warehouses" },
                    new SimpleType { Id = 2, Name = "Manage Regions" },
                     new SimpleType { Id = 3, Name = "Manage Locations" }
            };


            return PartialView();
        }

        // temp method for dhtmlx json bind test
        [AllowCrossSiteJson]
        public JsonResult GetTempWarhouseLocations()
        {
            var tmpQuery = new List<dynamic>();

            for (int i = 0; i <= 54; i++)
            {
                tmpQuery.Add(new
                {
                    Id = i,
                    data = new
                    {
                        LastScan = DateTime.Now,
                        Location = "zuydzuydwest",
                        Pieces = 5,
                        TotalPieces = 12,
                        TotalWeight = 25,
                        WeightUOM = "KG",
                        User = "Poloz Mukuch",
                        Warehouse = "Atata"
                    }
                });
            }

            return Json(new { rows = tmpQuery }, JsonRequestBehavior.AllowGet);
        }

        #region Add Edit Warehouse
        public PartialViewResult AddEditWarehouse()
        {
            WarehouseAddEdit model = new WarehouseAddEdit();
            return PartialView("_Warehouse", model);
        }

        public PartialViewResult GetWarehousById(long? id)
        {
            WarehouseAddEdit model = new WarehouseAddEdit();
            using (CommonUnit unit = new CommonUnit())
            {
                var tmpitem = unit.Context.UserWarehouses.Where(item => item.WarehouseId == id).FirstOrDefault();

                if (tmpitem != null)
                {
                    model.WarehouseId = tmpitem.WarehouseId;
                    model.WarehouseName = tmpitem.Warehouse.WarehouseName;
                    model.StationId = tmpitem.Warehouse.PortId;
                    model.ShellWarehouseId = tmpitem.Warehouse.ShellWarehouseId;
                    model.Address1 = tmpitem.Warehouse.Address;
                    model.Address2 = tmpitem.Warehouse.Address2;
                    model.AliasName = tmpitem.Warehouse.Code;
                    model.City = tmpitem.Warehouse.City;
                    model.CountryId = tmpitem.Warehouse.CountryId;
                    model.StateId = tmpitem.Warehouse.StateId;
                    model.Email = tmpitem.Warehouse.ContactEmail;
                    if (!String.IsNullOrWhiteSpace(tmpitem.Warehouse.Latitude) && !String.IsNullOrWhiteSpace(tmpitem.Warehouse.Longitude))
                    {
                        model.GeoLocation = tmpitem.Warehouse.Latitude + "," + tmpitem.Warehouse.Longitude;
                    }
                    model.ManagerName = tmpitem.Warehouse.Supervisor;
                    model.Phone = tmpitem.Warehouse.Phone;
                    model.Postal = tmpitem.Warehouse.PostalCode;
                }

                return PartialView("_WarehouseEditor", model);
            }
        }

        public JsonResult SaveWarehouse(WarehouseAddEdit model)
        {
            using (WarehouseUnit unit = new WarehouseUnit())
            {

                long id = unit.SaveWarehouse(model.ToBusinesModel());

                if (id > 0)
                {
                    return Json(new { data = "Ok" }, JsonRequestBehavior.AllowGet);
                }
                else // some error
                {
                    if (id == -2) // duplicate
                    {
                        string tmpMessage = String.Format("Warehouse {0} already exists", model.WarehouseName);
                        return Json(new { data = "Error", ErrorMessage = tmpMessage }, JsonRequestBehavior.AllowGet);
                    }
                    if (id == -3) // warehouse already mapped to shell warehouse
                    {
                        string tmpMessage = "Shell Warehouse already mapped, please select another Shell Warehouse.";
                        return Json(new { data = "Error", ErrorMessage = tmpMessage }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { data = "Error", ErrorMessage = "Server Error" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        #endregion


        #region Add Edit Region
        public PartialViewResult AddEditRegion()
        {
            RegionAddEdit model = new RegionAddEdit();
            return PartialView("_Region", model);
        }

        public PartialViewResult GetRegionById(long? id)
        {
            RegionAddEdit model = new RegionAddEdit();
            using (CommonUnit unit = new CommonUnit())
            {
                var tmpitem = unit.Context.WarehouseZones.Where(item => item.Id == id).FirstOrDefault();

                if (tmpitem != null)
                {
                    model.RegionId = tmpitem.Id;
                    model.RegionName = tmpitem.Zone;
                    model.StationId = tmpitem.Warehouse.PortId;
                    model.WarehouseId = tmpitem.WarehouseId;
                }

                return PartialView("_RegionEditor", model);
            }
        }

        public JsonResult SaveRegion(RegionAddEdit model)
        {

            using (WarehouseUnit unit = new WarehouseUnit())
            {
                long id = unit.SaveWarehouseZone(model.ToBusinessModel());

                if (id > 0)
                {
                    return Json(new { data = "Ok" }, JsonRequestBehavior.AllowGet);
                }
                else // some error
                {
                    if (id == -2) // duplicate
                    {
                        string tmpMessage = String.Format("Region {0} already exists", model.RegionName);
                        return Json(new { data = "Error", ErrorMessage = tmpMessage }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { data = "Error", ErrorMessage = "Server Error" }, JsonRequestBehavior.AllowGet);

                }
            }

        }

        #endregion


        #region Add Edit Location
        public PartialViewResult AddEditLocation()
        {
            LocationAddEdit model = new LocationAddEdit();
            return PartialView("_Location", model);
        }

        public PartialViewResult GetLocationById(long? id)
        {
            LocationAddEdit model = new LocationAddEdit();
            using (CommonUnit unit = new CommonUnit())
            {
                var tmpitem = unit.Context.WarehouseLocations.Where(item => item.Id == id).FirstOrDefault();

                if (tmpitem != null)
                {
                    model.LocationId = tmpitem.Id;
                    model.LocationName = tmpitem.Location;
                    model.StationId = tmpitem.Warehouse.PortId;
                    model.WarehouseId = tmpitem.WarehouseId;
                    model.RegionId = tmpitem.ZoneId;
                    model.LocationTypeId = tmpitem.LocationTypeId;
                    model.BarCode = tmpitem.Barcode;
                }

                return PartialView("_LocationEditor", model);
            }
        }

        public JsonResult SaveLocation(LocationAddEdit model)
        {

            using (WarehouseUnit unit = new WarehouseUnit())
            {

                long id = unit.SaveWarehouseLocation(model.ToBusinessModel());

                if (id > 0)
                {
                    return Json(new { data = "Ok" }, JsonRequestBehavior.AllowGet);
                }
                else // some error
                {
                    if (id == -2) // duplicate
                    {
                        string tmpMessage = String.Format("Location {0} already exists", model.LocationName);
                        return Json(new { data = "Error", ErrorMessage = tmpMessage }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { data = "Error", ErrorMessage = "Server Error" }, JsonRequestBehavior.AllowGet);

                }
            }

        }

        #endregion


        #region Grid methods
        [AllowCrossSiteJson]
        public JsonResult GetShipmentsTemp([DataSourceRequest] DataSourceRequest request, WarehouseManagement searchFilter)

MCH/MCH.Web/Views/WarehouseManagement/Index.cshtml

@{
    ViewBag.Title = "Warehouse Explorer";
    Layout = "~/Views/Shared/x_Layout.cshtml";
}

@section module{
    @Scripts.Render("~/bundles/warehouseExplorer")
}

<script>
    appWarehouseExplorer.rootURL = '@Url.Content("~")'
</script>


MCH/MCH.Web/Views/WarehouseManagement/_Location.cshtml
@using MCH.Web.Models.WarehouseManagement
@model LocationAddEdit

<script type="text/javascript">
    var LocationModel = {
        validator: null,
        cancel: function () {
            WahehouseManagementModel.windows.AddEditPopup().close();
        },

        saveLocation: function () {
            debugger;
            if (LocationModel.validator == null) {
                LocationModel.validator = $("#frmAddEditLocation").kendoValidator({
                    rules: WahehouseManagementModel.ValidationRules.Common,
                    validateOnBlur: true
                }).data("kendoValidator");
            }

            $("#btnSaveLocation").attr("disabled", "disabled");

            if (!LocationModel.validator.validate()) {
                $("#btnSaveLocation").removeAttr("disabled");
            }
            else {
                var formElementsJson = $("#frmAddEditLocation").serializeObject();
                var url = '@Url.Action("SaveLocation", "WarehouseManagement")';

                $.ajax({
                    //  async: true,
                    type: 'POST',
                    dataType: "json",
                    traditional: true,
                    url: url,
                    data: JSON.stringify(formElementsJson),
                    success: function (html) {
                        debugger;
                        $("#btnSaveLocation").removeAttr("disabled");
                        if (html.data == "Error") {
                            window.DIALOG_HANDLER.openAlert("Error", html.ErrorMessage);
                        }
                        else {
                            LocationModel.validator = null;
                            WahehouseManagementModel.windows.AddEditPopup().close();
                            // HWBGridModel.onSearch();
                        }

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        window.DIALOG_HANDLER.openAlert("Server Error", textStatus);
                        console.log(errorThrown);
                        $("#btnSaveLocation").removeAttr("disabled");
                    },
                    cache: false,
                    contentType: 'application/json, charset=utf-8',
                    processData: false
                });
            }
        },

        onLocationChange: function (e) {
            debugger;
            var id = parseInt(e.sender._selectedValue);
            if (isNaN(id))
                return;
            var url = '@Url.Action("GetLocationById", "WarehouseManagement")';

            $.ajax({
                type: 'POST',
                dataType: "html",
                traditional: true,
                url: url,
                data: { id: id },
                success: function (html) {
                    debugger;
                    $("#divLocationEditable").html(html);

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                },
                cache: false
            });

        },

        onStationChange: function (e) {
            var source = $("#StationId").data("kendoComboBox");
            var infl = $("#WarehouseId").data("kendoComboBox");
            infl.value("");
            infl.dataSource.read();
        },

        getStationId: function () {
            var id = $("#StationId").val();
            return { sId: id ? id : null }
        },

        onWarehouseChange: function (e) {
            debugger;
            var source = $("#WarehouseId").data("kendoComboBox");
            var infl = $("#RegionId").data("kendoComboBox");
            infl.value("");
            infl.dataSource.read();
        },

        getWarehouseId: function () {
            var id = $("#WarehouseId").val();
            return { sId: id ? id : null }
        },


        onRegionChange: function (e) {
            var source = $("#RegionId").data("kendoComboBox");
            var infl = $("#LocationId").data("kendoComboBox");
            infl.value("");
            infl.dataSource.read();
        },

        getRegionId: function () {
            var id = $("#RegionId").val();
            return { sId: id ? id : null }
        },

    }
</script>

<div class="container-fluid height100per paddingbottom30">
    <div class="row cm-wizard-container cm-heightcalc100-30">
        <form class="col-md-12 form-horizontal" id="frmAddEditLocation">
            <div class="form-group">
                <label class="col-lg-4 control-label required" id="">Station : </label>
                <div class="col-lg-7">
                    @(Html.Kendo().ComboBoxFor(m => m.StationId).DataSource(d =>
                                             d.Read(r => r.Action("GetPorts", "Common")
                                     )).DataTextField("Name").DataValueField("Id").Placeholder("- select -")
                                                             .Events(e => e.Change("LocationModel.onStationChange"))
                                     .HtmlAttributes(new
                                     {
                                         comboselected = "",
                                         data_comboselected_msg = "Station is invalid",
                                         inputempty = "",
                                         data_inputempty_msg = "Station is required"
                                     }).Filter(FilterType.Contains))
                    <span class="k-invalid-msg" data-for="StationId"></span>
                </div>
            </div>


            <div class="form-group">
                <label class="col-lg-4 control-label  required" id="">Warehouse : </label>
                <div class="col-lg-7">
                    @(Html.Kendo().ComboBoxFor(m => m.WarehouseId).DataSource(d =>
                                     d.Read(r => r.Action("GetWarehousesByStationId", "WarehouseManagement")
                                                                  .Data("LocationModel.getStationId")
                                     )).DataTextField("Name").DataValueField("Id").Placeholder("- select -")
                                                                                     .Events(e => e.Change("LocationModel.onWarehouseChange"))
                                     .HtmlAttributes(new
                                     {
                                         comboselected = "",
                                         data_comboselected_msg = "Warehouse is invalid",
                                         inputempty = "",
                                         data_inputempty_msg = "Warehouse is required"
                                     }).Filter(FilterType.Contains))
                    <span class="k-invalid-msg" data-for="WarehouseId"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-4 control-label  required" id="">Region : </label>
                <div class="col-lg-7">
                    @(Html.Kendo().ComboBoxFor(m => m.RegionId).DataSource(d =>
                                    d.Read(r => r.Action("GetRegionsByWarehouseId", "WarehouseManagement").Data("LocationModel.getWarehouseId")
                                     )).DataTextField("Name").DataValueField("Id").Placeholder("- select -")
                                                                                .Events(e => e.Change("LocationModel.onRegionChange"))
                                     .HtmlAttributes(new
                                     {
                                         comboselected = "",
                                         data_comboselected_msg = "Region is invalid",
                                         inputempty = "",
                                         data_inputempty_msg = "Region is required"
                                     }).Filter(FilterType.Contains))
                    <span class="k-invalid-msg" data-for="RegionId"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-4 control-label" id="">Location : </label>
                <div class="col-lg-7">
                    @(Html.Kendo().ComboBoxFor(m => m.LocationId).DataSource(d =>
                                            d.Read(r => r.Action("GetLocationsByRegionId", "WarehouseManagement").Data("LocationModel.getRegionId")
                                     )).DataTextField("Name").DataValueField("Id").Placeholder("- select -")
                                                                        .Events(e => e.Change("LocationModel.onLocationChange"))
                                     .HtmlAttributes(new
                                     {
                                     }).Filter(FilterType.Contains))
                </div>
            </div>

            <div id="divLocationEditable">
                @Html.Partial("_LocationEditor", Model)
            </div>

        </form>
    </div>
    <div class="row cm-bottom-right">
        <div class="col-md-12 pull-right buttons-wrapp">
            <div class="pull-right">
                <input type="button" class="k-button" value="Cancel" onclick="LocationModel.cancel()" />
                <input type="button" class="k-button k-primary" value="Save" id="btnSaveLocation" onclick="LocationModel.saveLocation()" />
            </div>
        </div>
    </div>
</div>

MCH/MCH.Web/Views/WarehouseManagement/_LocationEditor.cshtml
@using MCH.Web.Models.WarehouseManagement
@model LocationAddEdit


<div class="form-group">
    <label class="col-lg-4 control-label  required" id="">Location Type : </label>
    <div class="col-lg-7">
        @(Html.Kendo().ComboBoxFor(m => m.LocationTypeId).DataSource(d =>
                                    d.Read(r => r.Action("GetWarehouseLocationTypes", "WarehouseManagement")
                                     )).DataTextField("Name").DataValueField("Id").Placeholder("- select -")
                                     .HtmlAttributes(new
                                     {
                                         comboselected = "",
                                         data_comboselected_msg = "Location Type is invalid",
                                         inputempty = "",
                                         data_inputempty_msg = "Location Type is required"
                                         
                                     }).Filter(FilterType.Contains))
        <span class="k-invalid-msg" data-for="LocationTypeId"></span>
    </div>
</div>

<div class="form-group">
    <label class="col-lg-4 control-label required" id="">Location Name : </label>
    <div class="col-lg-7">
        @Html.TextBoxFor(m => m.LocationName, new { inputempty = "", data_inputempty_msg = "Name is required", @class = "k-textbox" })
        <span class="k-invalid-msg" data-for="LocationName"></span>
    </div>
</div>

<div class="form-group">
    <label class="col-lg-4 control-label required" id="">Barcode : </label>
    <div class="col-lg-7">
        @Html.TextBoxFor(m => m.BarCode, new { inputempty = "", data_inputempty_msg = "Barcode is required", @class = "k-textbox" })
        <span class="k-invalid-msg" data-for="Barcode"></span>
    </div>
</div>

MCH/MCH.Web/Views/WarehouseManagement/_RegionEditor.cshtml
@using MCH.Web.Models.WarehouseManagement
@model RegionAddEdit


<div class="form-group">
    <label class="col-lg-4 control-label required" id="">Region Name : </label>
    <div class="col-lg-7">
        @Html.TextBoxFor(m => m.RegionName, new { inputempty = "", data_inputempty_msg = "Name is required", @class = "k-textbox" })
        <span class="k-invalid-msg" data-for="RegionName"></span>
    </div>
</div>