MCH/MCH.Web/Models/Alert/TaskAlertsListModel.cs
using MCH.Web.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MCH.Web.Models.Alert
{
    public class TaskAlertsListModel
    {
        public long TaskId { get; set; }
        public long? FlightId { get; set; }
    }

    public class TaskAlertListFliter : DataTableFilter 
    {
        public long TaskId { get; set; }
        public long? FlightId { get; set; }
    }
}

MCH/MCH.Web/Controllers/AlertsController.cs
using MCH.BLL.Units;
using MCH.Web.Models.Alert;
using MCH.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCH.Web.Controllers
{
    public class AlertsController : BaseController
    {

        public PartialViewResult GetTaskAltersListView(TaskAlertsListModel model) 
        {
            using (CommonUnit unitOfWork = new CommonUnit())
            {
                var tmpTask = unitOfWork.Context.Tasks.SingleOrDefault(item => item.Id == model.TaskId);

                model.FlightId = tmpTask.EntityId;

                return PartialView("_TaskAlertsList", model);
            }
        }

        public JsonResult GetTaskAlertsList(TaskAlertListFliter filter) 
        {
            using (CommonUnit unitOfWork = new CommonUnit()) 
            {
                var tmpPort = unitOfWork.Context.Ports.SingleOrDefault(item=> item.Id == SessionManager.UserInfo.DefaultSiteId);

                var tmpAlters = unitOfWork.Context.GetFlightAlerts(tmpPort.IATACode, filter.FlightId, true).ToList();

                return Json(new
                {
                    sEcho = filter.sEcho,
                    iTotalRecords = tmpAlters.Count,
                    iTotalDisplayRecords = tmpAlters.Count,
                    aaData = tmpAlters
                }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

MCH/MCH.Web/Views/Alerts/_TaskAlertsList.cshtml
@model MCH.Web.Models.Alert.TaskAlertsListModel
<div class="row">
    <div class="col-md-12">
        <table id="tblTaskAlerts_@Model.TaskId" class="display dynamicTable" cellspacing="0" width="100%"></table>
    </div>
</div>

<script type="text/javascript">

    $(function () {

        var appendAlertListFilter = function (baseData) {
            if (baseData) {
                var tmpTaskId = '@Model.TaskId';
                var tmpFlightId = '@Model.FlightId';
                baseData.push({ "name": "TaskId", "value": tmpTaskId });
                baseData.push({ "name": "FlightId", "value": tmpFlightId });
            }
            return baseData;
        };

        $("#tblTaskAlerts_@Model.TaskId").dataTable({
            "order": [[0, "DESC"]],
            "iDisplayLength": 25,
            "bJQueryUI": true,
            "sScrollY": "250px",
            "bProcessing": true,
            "bPaginate": false,
            "bServerSide": true,
            "language": {
                "emptyTable": "No records found."
            },
            "sAjaxSource": "@Url.Action("GetTaskAlertsList", "Alerts")",
            "fnServerData": function (sSource, aoData, fnCallback, oSettings) {
                oSettings.jqXHR = $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": appendAlertListFilter(aoData),
                    "success": fnCallback
                });
            },
            "aoColumnDefs": [
                {
                    "aTargets": [0], "mData": "AlertMessage", "sTitle": 'Alert Message', "bSearchable": false, "bSortable": true
                },
                {
                    "aTargets": [1], "mData": "SetBy", "sTitle": 'Set By', "bSearchable": false, "bSortable": true
                },
                {
                    "aTargets": [2], "mData": "AlertDate", "sTitle": 'Alert Date', "bSearchable": false, "bSortable": true,
                    "mRender": function (data, type, full) {
                        return new Date().getDataTableColumn(data);
                    }
                }
            ]
        });
    });
</script>